version: "3.8"
services:
  backend:
    build: ./
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend-app
    ports:
      - "6114:3000"
    depends_on:
      - backend

# docker-compose up --build
